global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '192.168.1.23:9093'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['192.168.1.23:9093']
